# Generated by Django 5.2.4 on 2025-07-25 10:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklist', '0003_productionline_visitsachieved'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitsachieved',
            name='added_by',
            field=models.ForeignKey(blank=True, help_text='User who added this record (optional)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visits_added', to=settings.AUTH_USER_MODEL),
        ),
    ]
