# Generated by Django 5.2.4 on 2025-07-25 20:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklist', '0006_paymentcollected'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewLead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=255)),
                ('contact', models.CharField(max_length=255)),
                ('designation', models.CharField(choices=[('Owner', 'Owner'), ('Engineer', 'Engineer'), ('Contractor', 'Contractor')], max_length=20)),
                ('location', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('added_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('production_line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leads', to='checklist.productionline')),
            ],
        ),
    ]
