# Generated by Django 5.2.4 on 2025-07-26 06:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklist', '0007_newlead'),
    ]

    operations = [
        migrations.CreateModel(
            name='RouteClient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=255, verbose_name='Client / Company Name')),
                ('contact', models.CharField(max_length=100)),
                ('purpose', models.CharField(choices=[('NEW', 'New'), ('FU', 'Follow Up'), ('CLOSING', 'Closing')], max_length=10)),
                ('priority', models.CharField(choices=[('HIGH', 'High'), ('MED', 'Medium'), ('LOW', 'Low')], max_length=10)),
                ('next_step', models.TextField(verbose_name='Your Next Step')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('added_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='added_route_clients', to=settings.AUTH_USER_MODEL)),
                ('production_line', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='route_clients', to='checklist.productionline')),
            ],
        ),
    ]
