# Generated by Django 5.2.4 on 2025-07-27 17:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklist', '0008_routeclient'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='paymentcollected',
            options={'verbose_name': 'Payment collected', 'verbose_name_plural': 'Payment collected'},
        ),
        migrations.AlterModelOptions(
            name='visitsachieved',
            options={'verbose_name': 'Visits achieved', 'verbose_name_plural': 'Visits achieved'},
        ),
        migrations.AlterField(
            model_name='paymentcollected',
            name='payment_amount',
            field=models.DecimalField(decimal_places=2, max_digits=16),
        ),
        migrations.CreateModel(
            name='DailyTarget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned', models.PositiveIntegerField()),
                ('to_be_achieved', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('added_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='daily_targets_added', to=settings.AUTH_USER_MODEL)),
                ('production_line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_targets', to='checklist.productionline')),
            ],
            options={
                'verbose_name': 'Daily target',
                'verbose_name_plural': 'Daily targets',
                'ordering': ['-created_at'],
            },
        ),
    ]
