# Generated by Django 5.2.4 on 2025-07-28 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklist', '0009_alter_paymentcollected_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='user_type',
        ),
        migrations.AddField(
            model_name='customuser',
            name='branch',
            field=models.CharField(blank=True, choices=[('CHANIKA', 'Chanika'), ('MWANZA', 'Mwanza'), ('SINGIDA', 'Singida'), ('MIKOCHENI', 'Mikocheni')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='contact',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='position',
            field=models.CharField(blank=True, choices=[('SALE_OFFICER', 'Sale Officer'), ('MANAGER', 'Manager'), ('OPERATE_OFFICER', 'Operate Officer')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='zone',
            field=models.CharField(blank=True, choices=[('CENTRAL', 'Central Zone'), ('LAKE', 'Lake Zone')], max_length=20, null=True),
        ),
    ]
