# Generated by Django 5.2.4 on 2025-07-29 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklist', '0011_remove_customuser_username_customuser_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='newlead',
            name='status',
            field=models.CharField(choices=[('opened', 'Opened'), ('approved', 'Approved'), ('resubmite', 'Resubmit')], default='opened', max_length=10),
        ),
        migrations.AddField(
            model_name='orderquotation',
            name='status',
            field=models.CharField(choices=[('opened', 'Opened'), ('approved', 'Approved'), ('resubmite', 'Resubmit')], default='opened', max_length=10),
        ),
        migrations.AddField(
            model_name='paymentcollected',
            name='status',
            field=models.CharField(choices=[('opened', 'Opened'), ('approved', 'Approved'), ('resubmite', 'Resubmit')], default='opened', max_length=10),
        ),
        migrations.AddField(
            model_name='routeclient',
            name='status',
            field=models.CharField(choices=[('opened', 'Opened'), ('approved', 'Approved'), ('resubmite', 'Resubmit')], default='opened', max_length=10),
        ),
        migrations.AddField(
            model_name='visitsachieved',
            name='status',
            field=models.CharField(choices=[('opened', 'Opened'), ('approved', 'Approved'), ('resubmite', 'Resubmit')], default='opened', max_length=10),
        ),
    ]
