# Generated by Django 5.2.4 on 2025-07-29 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklist', '0013_alter_visitsachieved_added_by_formsubmission_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='formsubmission',
            name='status',
            field=models.CharField(choices=[('opened', 'Opened'), ('approved', 'Approved'), ('resubmite', 'Resubmit')], default='opened', max_length=10),
        ),
    ]
