# Generated by Django 5.2.4 on 2025-07-29 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklist', '0014_formsubmission_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formsubmission',
            name='status',
            field=models.CharField(choices=[('opened', 'Opened'), ('reviewed', 'Reviewed'), ('rejected', 'Rejected'), ('approved', 'Approved'), ('resubmite', 'Resubmit')], default='opened', max_length=10),
        ),
        migrations.AlterField(
            model_name='newlead',
            name='status',
            field=models.CharField(choices=[('opened', 'Opened'), ('reviewed', 'Reviewed'), ('rejected', 'Rejected'), ('approved', 'Approved'), ('resubmite', 'Resubmit')], default='opened', max_length=10),
        ),
        migrations.AlterField(
            model_name='orderquotation',
            name='status',
            field=models.CharField(choices=[('opened', 'Opened'), ('reviewed', 'Reviewed'), ('rejected', 'Rejected'), ('approved', 'Approved'), ('resubmite', 'Resubmit')], default='opened', max_length=10),
        ),
        migrations.AlterField(
            model_name='paymentcollected',
            name='status',
            field=models.CharField(choices=[('opened', 'Opened'), ('reviewed', 'Reviewed'), ('rejected', 'Rejected'), ('approved', 'Approved'), ('resubmite', 'Resubmit')], default='opened', max_length=10),
        ),
        migrations.AlterField(
            model_name='routeclient',
            name='status',
            field=models.CharField(choices=[('opened', 'Opened'), ('reviewed', 'Reviewed'), ('rejected', 'Rejected'), ('approved', 'Approved'), ('resubmite', 'Resubmit')], default='opened', max_length=10),
        ),
        migrations.AlterField(
            model_name='visitsachieved',
            name='status',
            field=models.CharField(choices=[('opened', 'Opened'), ('reviewed', 'Reviewed'), ('rejected', 'Rejected'), ('approved', 'Approved'), ('resubmite', 'Resubmit')], default='opened', max_length=10),
        ),
    ]
