# Generated by Django 5.2.4 on 2025-07-30 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklist', '0016_formsubmission_status_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderquotation',
            name='quotation',
            field=models.DecimalField(decimal_places=2, max_digits=17),
        ),
    ]
