# Generated by Django 5.2.4 on 2025-07-31 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklist', '0017_alter_orderquotation_quotation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newlead',
            name='location',
        ),
        migrations.AddField(
            model_name='newlead',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='newlead',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
    ]
