# Generated by Django 5.2.4 on 2025-07-31 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklist', '0018_remove_newlead_location_newlead_latitude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newlead',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=13, null=True),
        ),
        migrations.AlterField(
            model_name='newlead',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=13, null=True),
        ),
    ]
