# Generated by Django 5.2.4 on 2025-08-01 05:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklist', '0020_alter_newlead_latitude_alter_newlead_longitude'),
    ]

    operations = [
        migrations.RenameField(
            model_name='formsubmission',
            old_name='status_updated_at',
            new_name='manager1_reviewed_at',
        ),
        migrations.RemoveField(
            model_name='formsubmission',
            name='status',
        ),
        migrations.RemoveField(
            model_name='formsubmission',
            name='status_updated_by',
        ),
        migrations.AddField(
            model_name='formsubmission',
            name='final_status',
            field=models.CharField(choices=[('opened', 'Opened'), ('rejected', 'Rejected'), ('approved', 'Approved'), ('resubmite', 'Resubmit')], default='opened', max_length=10),
        ),
        migrations.AddField(
            model_name='formsubmission',
            name='manager1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='first_reviews', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='formsubmission',
            name='manager1_comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='formsubmission',
            name='manager1_status',
            field=models.CharField(blank=True, choices=[('opened', 'Opened'), ('rejected', 'Rejected'), ('approved', 'Approved'), ('resubmite', 'Resubmit')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='formsubmission',
            name='manager2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='second_reviews', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='formsubmission',
            name='manager2_comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='formsubmission',
            name='manager2_reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='formsubmission',
            name='manager2_status',
            field=models.CharField(blank=True, choices=[('opened', 'Opened'), ('rejected', 'Rejected'), ('approved', 'Approved'), ('resubmite', 'Resubmit')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='newlead',
            name='status',
            field=models.CharField(choices=[('opened', 'Opened'), ('rejected', 'Rejected'), ('approved', 'Approved'), ('resubmite', 'Resubmit')], default='opened', max_length=10),
        ),
        migrations.AlterField(
            model_name='orderquotation',
            name='status',
            field=models.CharField(choices=[('opened', 'Opened'), ('rejected', 'Rejected'), ('approved', 'Approved'), ('resubmite', 'Resubmit')], default='opened', max_length=10),
        ),
        migrations.AlterField(
            model_name='paymentcollected',
            name='status',
            field=models.CharField(choices=[('opened', 'Opened'), ('rejected', 'Rejected'), ('approved', 'Approved'), ('resubmite', 'Resubmit')], default='opened', max_length=10),
        ),
        migrations.AlterField(
            model_name='routeclient',
            name='status',
            field=models.CharField(choices=[('opened', 'Opened'), ('rejected', 'Rejected'), ('approved', 'Approved'), ('resubmite', 'Resubmit')], default='opened', max_length=10),
        ),
        migrations.AlterField(
            model_name='visitsachieved',
            name='status',
            field=models.CharField(choices=[('opened', 'Opened'), ('rejected', 'Rejected'), ('approved', 'Approved'), ('resubmite', 'Resubmit')], default='opened', max_length=10),
        ),
    ]
