# Generated by Django 5.2.4 on 2025-08-01 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklist', '0021_rename_status_updated_at_formsubmission_manager1_reviewed_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='formsubmission',
            name='dispatch_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
