# Generated by Django 5.2.4 on 2025-08-01 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklist', '0022_formsubmission_dispatch_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formsubmission',
            name='dispatch_time',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='branch',
            field=models.CharField(blank=True, choices=[('Chanika', 'Chanika'), ('Mikocheni', 'Mikocheni'), ('Morogoro', 'Morogoro'), ('Zanzibar', 'Zanzibar'), ('ANDO HQ', 'ANDO HQ'), ('Dodoma', 'Dodoma'), ('Singida', 'Singida'), ('Tabora', 'Tabora'), ('Mbeya', 'Mbeya'), ('Tunduma', 'Tunduma'), ('Arusha', 'Arusha'), ('Moshi', 'Moshi'), ('Mwanza', 'Mwanza'), ('Geita', 'Geita')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='position',
            field=models.CharField(blank=True, choices=[('Head of Sales', 'Head of Sales'), ('Facilitator', 'Facilitator'), ('Product Brand Manager', 'Product Brand Manager'), ('Corporate Manager', 'Corporate Manager'), ('Corporate Officer', 'Corporate Officer'), ('Zonal Sales Executive', 'Zonal Sales Executive'), ('Mobile Sales Officer', 'Mobile Sales Officer'), ('Desk Sales Officer', 'Desk Sales Officer'), ('Admin', 'Admin')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='zone',
            field=models.CharField(blank=True, choices=[('Coast Zone', 'Coast Zone'), ('Corporate', 'Corporate'), ('Central Zone', 'Central Zone'), ('Southern Zone', 'Southern Zone'), ('Northern Zone', 'Northern Zone'), ('Lake Zone', 'Lake Zone')], max_length=100, null=True),
        ),
    ]
