# Generated by Django 5.2.4 on 2025-08-01 19:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklist', '0023_remove_formsubmission_dispatch_time_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='formsubmission',
            old_name='manager1_comment',
            new_name='brand_manager_comment',
        ),
        migrations.RenameField(
            model_name='formsubmission',
            old_name='manager1_reviewed_at',
            new_name='brand_manager_reviewed_at',
        ),
        migrations.RenameField(
            model_name='formsubmission',
            old_name='manager2_comment',
            new_name='facilitator_comment',
        ),
        migrations.RenameField(
            model_name='formsubmission',
            old_name='manager2_reviewed_at',
            new_name='facilitator_reviewed_at',
        ),
        migrations.RemoveField(
            model_name='formsubmission',
            name='manager1',
        ),
        migrations.RemoveField(
            model_name='formsubmission',
            name='manager1_status',
        ),
        migrations.RemoveField(
            model_name='formsubmission',
            name='manager2',
        ),
        migrations.RemoveField(
            model_name='formsubmission',
            name='manager2_status',
        ),
        migrations.AddField(
            model_name='formsubmission',
            name='brand_manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='brand_manager_reviews', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='formsubmission',
            name='brand_manager_status',
            field=models.CharField(blank=True, choices=[('opened', 'Opened'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('resubmite', 'Resubmite')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='formsubmission',
            name='facilitator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='facilitator_reviews', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='formsubmission',
            name='facilitator_status',
            field=models.CharField(blank=True, choices=[('opened', 'Opened'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('resubmite', 'Resubmite')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='formsubmission',
            name='zonal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='zonal_reviews', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='formsubmission',
            name='zonal_comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='formsubmission',
            name='zonal_reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='formsubmission',
            name='zonal_status',
            field=models.CharField(blank=True, choices=[('opened', 'Opened'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('resubmite', 'Resubmite')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='formsubmission',
            name='final_status',
            field=models.CharField(choices=[('opened', 'Opened'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('resubmite', 'Resubmite')], default='opened', max_length=10),
        ),
        migrations.AlterField(
            model_name='newlead',
            name='status',
            field=models.CharField(choices=[('opened', 'Opened'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('resubmite', 'Resubmite')], default='opened', max_length=10),
        ),
        migrations.AlterField(
            model_name='orderquotation',
            name='status',
            field=models.CharField(choices=[('opened', 'Opened'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('resubmite', 'Resubmite')], default='opened', max_length=10),
        ),
        migrations.AlterField(
            model_name='paymentcollected',
            name='status',
            field=models.CharField(choices=[('opened', 'Opened'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('resubmite', 'Resubmite')], default='opened', max_length=10),
        ),
        migrations.AlterField(
            model_name='routeclient',
            name='status',
            field=models.CharField(choices=[('opened', 'Opened'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('resubmite', 'Resubmite')], default='opened', max_length=10),
        ),
        migrations.AlterField(
            model_name='visitsachieved',
            name='status',
            field=models.CharField(choices=[('opened', 'Opened'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('resubmite', 'Resubmite')], default='opened', max_length=10),
        ),
    ]
