# Generated by Django 5.2.4 on 2025-08-01 19:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklist', '0024_rename_manager1_comment_formsubmission_brand_manager_comment_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='formsubmission',
            old_name='brand_manager_comment',
            new_name='product_comment',
        ),
        migrations.RenameField(
            model_name='formsubmission',
            old_name='brand_manager_reviewed_at',
            new_name='product_reviewed_at',
        ),
        migrations.RenameField(
            model_name='formsubmission',
            old_name='brand_manager_status',
            new_name='product_status',
        ),
        migrations.RemoveField(
            model_name='formsubmission',
            name='brand_manager',
        ),
        migrations.AddField(
            model_name='formsubmission',
            name='product_manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_reviews', to=settings.AUTH_USER_MODEL),
        ),
    ]
