# Generated by Django 5.2.4 on 2025-08-01 20:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklist', '0025_rename_brand_manager_comment_formsubmission_product_comment_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='formsubmission',
            old_name='product_comment',
            new_name='product_manager_comment',
        ),
        migrations.RenameField(
            model_name='formsubmission',
            old_name='product_reviewed_at',
            new_name='product_manager_reviewed_at',
        ),
        migrations.RenameField(
            model_name='formsubmission',
            old_name='product_status',
            new_name='product_manager_status',
        ),
        migrations.RenameField(
            model_name='formsubmission',
            old_name='zonal',
            new_name='zonal_reviewer',
        ),
        migrations.AlterField(
            model_name='formsubmission',
            name='product_manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_manager_reviews', to=settings.AUTH_USER_MODEL),
        ),
    ]
