# Generated by Django 5.2.4 on 2025-08-02 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklist', '0026_rename_product_comment_formsubmission_product_manager_comment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='formsubmission',
            name='dispatch_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
