from django.urls import path
from . import views

urlpatterns = [
    path('manager-dashbord', views.index, name='index'),
    path('', views.login_user, name='login'),
    path('auth/register/', views.register, name='register'),
    path('users/dashboard/', views.dashboard, name='dashboard'),
    path('users/checklist/', views.checklist, name='checklist'),
    path('logout/', views.logout_user, name='logout'),
    path('visits/add/', views.add_visit, name='add_visit'),
    path('visits/edit/<int:visit_id>/', views.edit_visit, name='edit_visit'),
    path('visits/<int:visit_id>/', views.visit_detail, name='visit_detail'),
    path('visits/delete/<int:visit_id>/', views.delete_visit, name='delete_visit'),
    path('quotations/', views.quotations_list, name='quotations_list'),
    path('quotations/add/', views.add_quotation, name='add_quotation'),
    path('quotations/edit/<int:quotation_id>/', views.edit_quotation, name='edit_quotation'),
    path('quotations/delete/<int:quotation_id>/', views.delete_quotation, name='delete_quotation'),
    path('payments/', views.payment_list, name='payment_list'),
    path('payments/add/', views.add_payment, name='add_payment'),
    path('payments/edit/<int:pk>/', views.edit_payment, name='edit_payment'),
    path('payments/delete/<int:pk>/', views.delete_payment, name='delete_payment'),
    path('payments/view/<int:pk>/', views.view_payment, name='view_payment'),
    path('leads/', views.lead_list, name='lead_list'),
    path('leads/add/', views.add_lead, name='add_lead'),
    path('leads/edit/<int:pk>/', views.edit_lead, name='edit_lead'),
    path('leads/delete/<int:pk>/', views.delete_lead, name='delete_lead'),
     path("leads/<int:pk>/", views.lead_detail_view, name="view_lead"),
     path('routes/', views.route_clients, name='route_clients'),
    path('routes/edit/<int:pk>/', views.edit_route_client, name='edit_route_client'),
    path('routes/delete/<int:pk>/', views.delete_route_client, name='delete_route_client'),
       path('routes/view/<int:pk>/', views.view_route_client, name='view_route_client'),
       path('visit/<int:id>/', views.manager_view_visit_achieved, name='manager_view_visit_achieved'),
       path('order-quotations/', views.manager_view_order_quotations, name='manager_view_order_quotations'),
       path('order-quotations/<int:id>/', views.view_order_quotation_detail, name='manager_view_order_quotation_detail'),
      path('manager-payments/', views.manager_view_payments_collected, name='manager_view_payments_collected'),
    path('manager-payments/<int:id>/', views.manager_view_payment_detail, name='manager_view_payment_detail'),
     path('visits/', views.visits_achieved_list, name='visits_achieved_list'),
     path('quotations/view/<int:quotation_id>/', views.view_quotation, name='view_quotation'),
     path('manager/visits-achieved/', views.manager_visits_achieved, name='manager_visits_achieved'),
     path('manager-leads/', views.manager_view_leads, name='manager_view_leads'),
    path('manager-leads/<int:id>/', views.manager_view_lead_detail, name='manager_view_lead_detail'),
    path('manager-route-clients/', views.manager_view_route_clients, name='manager_view_route_clients'),
    path('manager-route-clients/<int:id>/', views.manager_view_route_client_detail, name='manager_view_route_client_detail'),
    path('production-lines/', views.manager_view_production_lines, name='manager_view_production_lines'),
    path('production-lines/<int:id>/', views.manager_view_production_line_detail, name='manager_view_production_line_detail'),
    path('users/', views.user_list_view, name='manager_view_users'),
    path('users/<int:user_id>/', views.user_detail_view, name='manager_view_user_detail'),
    path('profile/', views.user_profile, name='manager_user_profile'),
     path('change-password/', views.change_password, name='change_password'),


]
